add_newline = false

format = """\
  $username\
  $hostname\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $env_var\
  $line_break\
  $cmd_duration\
  $jobs\
  $time\
  $memory_usage\
  $character\
  """

[character]
success_symbol = "[❯❯](bold green)"
error_symbol = "[❯❯](bold red)"

[line_break]
disabled = true

[cmd_duration]
min_time = 500
format = "took [$duration]($style) "

[hostname]
ssh_only = true

[directory]
truncation_length = 64
format = "[$path](blue)[$read_only](fg:208) "
truncate_to_repo = false

[username]
style_root = "bold red"
style_user = "bold yellow"
show_always = false
disabled = false

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ](fg:70) '

[git_status]
format = '[\[ $all_status$ahead_behind \]](fg:250) '
conflicted = " ⚔ "
ahead = "⇡{$count}"
behind = "⇣{$count}"
diverged = "⇕"
up_to_date = ""
untracked = "?{$count}"
stashed = "$"
modified = "!{$count}"
staged = "+{$count}"
renamed = "»{$count}"
deleted = "✘{$count}"
style = "bold red"
