add_newline = false

format = """\
  $username\
  $hostname\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $env_var\
  $line_break\
  $cmd_duration\
  $jobs\
  $time\
  $memory_usage\
  $character\
  """

[character]
success_symbol = "[â¯â¯](bold green)"
error_symbol = "[â¯â¯](bold red)"

# [line_break]
# disabled = true

[cmd_duration]
min_time = 500
format = "took [$duration]($style) "

[hostname]
ssh_only = true

[directory]
truncation_length = 64
truncate_to_repo = false
format = "[$path](blue bold)[$read_only](fg:208) "

[username]
style_root = "bold red"
style_user = "bold yellow"
show_always = false
disabled = false

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ](fg:70) '

[git_status]
format = '$all_status$ahead_behind'
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨$count "
behind = "ğŸ˜°$count "
diverged = "îœ¨ "
up_to_date = ""
untracked = "ğŸ‘€$count "
stashed = "ğŸ“¦ "
modified = "[!$count ](yellow bold)"
staged = "[ï§$count ](green bold)"
renamed = "Â»$count "
deleted = "[ïš¿$count ](red bold)"
